   
- hosts: all
  become: True
  roles:
    - set-hostname
    - maintainer-users
    - set-time
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
  tasks:
    - include: 'tasks/main.yml'
